input_shape: [320, 320, 3]
num_classes: 14
filters: [32, 64, 128]
dense_units: 128
dropout: 0.5
activation: relu
kernel_initializer: he_normal
weight_decay: 1e-4 # more of a training thing
bn_momentum: 0.9
bn_epsilon: 1e-5
