
defaults:
  - _self_
  - model_type: cnn
  - preprocessor: preprocessor
  - models: cnn
  - training: cnn
  #- override hydra/launcher: joblib


random_state: 42
experiment_name: deep_chest


#run_tuning_name: tuning
#run_training_name: training
#hydra:
#  launcher:
#    n_jobs: 2


